-- 1. What is the total revenue generated by male vs. female customers?
SELECT
	gender,
    SUM(purchase_amount_usd) AS revenue_generated
FROM customer
GROUP BY gender
;





-- 2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
	-- COUNT(DISTINCT customer_id)
    customer_id,
    purchase_amount_usd
FROM customer
	WHERE discount_applied = 'Yes'
    AND purchase_amount_usd > (SELECT AVG(purchase_amount_usd) FROM customer)
;






-- 3. Which are the top 5 products with the highest average review rating?
SELECT
	item_purchased AS products,
    ROUND(AVG(review_rating), 2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5
;




-- 4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT
	shipping_type,
	ROUND(AVG(purchase_amount_usd), 2) AS avg_purchase_amount
FROM customer
	WHERE shipping_type IN ('Standard', 'Express')
GROUP BY 1
ORDER BY 2 DESC
;








-- 5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT
	CASE
		WHEN subscription_status = 'Yes' THEN 'Subscribed'
        ELSE 'No Subscription'
	END AS custumer_type,
	AVG(purchase_amount_usd) AS avg_spend,
    SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY 1
ORDER BY 2 DESC
;




-- 6. Which 5 products have the highest percentage of purchases with discounts applied?
WITH discount_purchase AS (
SELECT
	item_purchased AS product,
    SUM(CASE WHEN discount_applied = 'Yes' THEN purchase_amount_usd END) AS discount_purchase,
    SUM(CASE WHEN discount_applied != 'Yes' THEN purchase_amount_usd END) AS no_discount
FROM customer
GROUP BY 1
)

SELECT
	*,
    ROUND(100 * (discount_purchase/(discount_purchase + no_discount)), 2) AS percent_discount_purchases
FROM discount_purchase
ORDER BY 4 DESC
;




-- 7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
SELECT
	CASE 
		WHEN previous_purchases <= 5 THEN 'New'
		WHEN previous_purchases <= 20 THEN 'Returning'
		ELSE 'Loyal'
    END AS segments,
    COUNT(*) AS segment_count
FROM customer
GROUP BY 1
ORDER BY 2 DESC
;




-- 8. What are the top 3 most purchased products within each category? 
WITH ranks AS (
SELECT
	category,
    item_purchased,
    COUNT(customer_id) as orders,
    RANK() OVER (PARTITION BY category ORDER BY SUM(purchase_amount_usd) DESC) AS ranking
FROM customer
GROUP BY 1, 2
)
SELECT
	*
FROM ranks
	WHERE ranking <= 3
 ;   



-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
	CASE
		WHEN previous_purchases > 5 AND subscription_status = 'Yes' THEN 'Repeat Subscribers'
        ELSE 'Others'
	END AS class,
    COUNT(customer_id) AS customers
FROM customer
GROUP BY 1
;


-- 10. What is the revenue contribution of each age group? 
 SELECT
	age_group,
    SUM(purchase_amount_usd) AS revenue
FROM customer
GROUP BY 1
ORDER BY 2 DESC
;